Repository AbirAahammed/E-card, pull requests merged in 2021-02, with the labels that each got.

#14 readme-update
  .gitignore
  README.md
Labels: documentation

#16 Documentation/read me
  .gitignore
  README.md
Labels: documentation, enhancement

#18 Added Proposal document.
  Proposal.docx
Labels: documentation

#17 Update readme:
  Proposal.docx
  README.md
Labels: documentation, enhancement

#21 Added missing meeting minutes from Jan 20th
  Meetings/Minutes/Meeting_Minutes_Jan20th.pdf
Labels: documentation

#19 Added notes for Sprint 1 meetings
  Meetings/Discussion/1 - Project Ideas - January 20th.md
  Meetings/Discussion/2 - App name & Sprint 1 Discussion - January 25th.md
  Meetings/Discussion/3 - Sprint 1 Finalization & Presentation Discussion - Feb 3rd.md
Labels: documentation

#32 Updating information in the proposal document.
  Proposal.docx
Labels: bug, documentation

#34 Added meeting notes
  Meetings/Discussion/4 - Sprint 2 Discussion - February 15th.md
Labels: documentation

#47 Created classes for common objects in the Data Layer
  app/src/main/java/redbull/ecard/DataLayer/Address.java
  app/src/main/java/redbull/ecard/DataLayer/Card.java
  app/src/main/java/redbull/ecard/DataLayer/Contact.java
  app/src/main/java/redbull/ecard/DataLayer/Name.java
  app/src/main/java/redbull/ecard/DataLayer/Profile.java
Labels: High Priority, Tasks, enhancement
